import { jsPDF } from "jspdf";

export const generateReport = (profile, result) => {
  const doc = new jsPDF();

  const today = new Date().toLocaleDateString("en-IN");

  const recommendations = result.prediction.includes("Low")
    ? [
        "Maintain a balanced diet",
        "Exercise regularly",
        "Sleep 7-8 hours",
        "Track your menstrual cycle",
      ]
    : [
        "Consult a gynecologist",
        "Exercise regularly",
        "Maintain a healthy diet",
        "Reduce processed foods",
        "Track your menstrual cycle",
      ];

  let y = 20;

  doc.setFontSize(20);
  doc.text("PCOS HEALTH REPORT", 20, y);

  y += 12;

  doc.setFontSize(12);
  doc.text("Generated by PCOS Early Detection Platform", 20, y);

  y += 15;

  doc.setFontSize(15);
  doc.text("Patient Information", 20, y);

  y += 10;
  doc.setFontSize(12);
  doc.text(`Name: ${profile?.name || "User"}`, 20, y);

  y += 8;
  doc.text(`Age: ${profile?.age || "-"}`, 20, y);

  y += 15;

  doc.setFontSize(15);
  doc.text("Prediction Result", 20, y);

  y += 10;

  doc.setFontSize(12);
  doc.text(`Prediction: ${result.prediction}`, 20, y);

  y += 8;
  doc.text(`Confidence: ${result.confidence}%`, 20, y);

  y += 8;
  doc.text(`Assessment Date: ${today}`, 20, y);

  y += 15;

  doc.setFontSize(15);
  doc.text("Recommendations", 20, y);

  y += 10;

  doc.setFontSize(12);

  recommendations.forEach((item) => {
    doc.text(`• ${item}`, 25, y);
    y += 8;
  });

  y += 12;

  doc.setFontSize(11);
  doc.text(
    "This AI prediction is intended for screening purposes only and should not replace professional medical advice.",
    20,
    y,
    { maxWidth: 170 }
  );

  doc.save("PCOS_Health_Report.pdf");
};